[package]
name = "near-units"
version = "0.1.0"
authors = ["Near Inc <team@near.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-units-core = { path = "../core" }
near-units-macro = { path = "../macro" }
